# Generated by Django 5.1.1 on 2025-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.IntegerField(auto_created=442151, blank=True, verbose_name='Код подтверждения'),
        ),
    ]
