# Generated by Django 5.1.1 on 2025-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.IntegerField(verbose_name='Код подтверждения'),
        ),
    ]
